---
- name: 'Agrega {{ espacio }} al filesystem {{ filesystem }}'
  hosts: '{{ target }}'
  become: yes
  vars:
    target: g500603vm201
    espacio: "1.5g"
    filesystem: root
    dispositivo: sdc
  tasks:
  - name: use Jinja2 template to configure script
    template: 
      src: agregaEspacioFilesystem.j2 
      dest: /root/agregaEspacioFilesystem.sh
    tags:
      script

  - name: Execute the script
    shell: sh /root/agregaEspacioFilesystem.sh
    register: result_info
    tags:
      runScript

  - name: Display output
    debug:
      msg: "{{ result_info.stdout_lines }}"
    tags:
      displayOutput

  - name: Remove script
    ansible.builtin.file:
      path: /root/agregaEspacioFilesystem.sh
      state: absent
    tags:
      removeScript
