---
- name: Agrega disco recien presentado
  hosts: '{{ target }}'
  become: yes
  vars:
    target: g500603vm201
  tasks:
  - name: agrega disco recien presentado
    copy: src=templates/agregaDiscoPresentado.j2 dest=/root/agregaDiscoPresentado.sh
    tags:
      script

  - name: Execute the script
    shell: sh /root/agregaDiscoPresentado.sh
    register: result_info
    tags:
      executeScript

  - name: Display output
    debug:
      msg: "{{ result_info.stdout_lines }}"
    tags:
      display

  - name: Remove script
    ansible.builtin.file:
      path: /root/agregaDiscoPresentado.sh
      state: absent
    tags:
      removeScript
