---
- name: command df con filtros
  hosts: "{{ target }}"
  gather_facts: no
  vars:
    target: g500603vm201
  tasks:
    - name: Return motd to registered var
      ansible.builtin.shell: "/usr/bin/df -h | grep -e boot -e root -e '%./var'$"
      register: command_result
      tags:
        shell

    - name: Display command result
      debug:
        msg: "{{ command_result.stdout_lines }}"
      tags:
        display
