---
- name: Usar plantilla Jinja2 con condicionales
  hosts: "{{ target }}"
  gather_facts: yes
  vars:
    target: g500603vm201
  tasks:
    - name: Crear archivo desde plantilla
      template:
        src: templates/conditionals.j2
        dest: /tmp/conditionals.txt
