---
- name: Elimina SUMA-ar definition
  hosts: ar-suma
  become: yes
  vars:
    serverToEliminate: iq3-ci
  tasks:

  - name: Create file from template
    template:
      src: templates/eliminaEnSuma.j2
      dest: /root/eliminaEnSuma.sh

  - name: Execute the script
    command: sh /root/eliminaEnSuma.sh
    ignore_errors: true

  - name: Remove file
    ansible.builtin.file:
      path: /root/eliminaEnSuma.sh
      state: absent
