---
- name: Elimina SUMA definition
  hosts: '{{ pais }}-suma'
  become: yes
  vars:
    pais: cl
  tasks:

  - name: Create file from template
    template:
      src: templates/eliminaEnSuma.j2
      dest: /root/eliminaEnSuma.sh
    tags:
      script

  - name: Execute the script
    command: sh /root/eliminaEnSuma.sh
    ignore_errors: true
    tags:
      command

  - name: Remove file
    ansible.builtin.file:
      path: /root/eliminaEnSuma.sh
      state: absent
    tags:
      removeScript
