---
- name: Elimina SUMA definition
  hosts: cl-suma
  become: yes
  tasks:

  - name: Create file from template
    template:
      src: templates/eliminaEnSuma.j2
      dest: /root/eliminaEnSuma.sh

  - name: Execute the script
    command: sh /root/eliminaEnSuma.sh

  - name: Remove file
    ansible.builtin.file:
      path: /root/eliminaEnSuma.sh
      state: absent
