---
- name: Playbook getgroups
  hosts: brasil
  become: True
  tasks:
    - name: Get all groups
      ansible.builtin.getent:
        database: group
        split: ':'
    - ansible.builtin.debug:
        var: ansible_facts.getent_group
