---
- name: Instala Agente AWS
  hosts: '{{ target }}'
  become: yes
  tasks:
  - name: use Jinja2 template to configure script
    template:
      src: instalAgenteAWS.j2
      dest: /root/instalAgenteAWS.sh

  - name: Execute the script
    shell: sh /root/instalAgenteAWS.sh
    register: result_info

  - name: Display output
    debug:
      msg: "{{ result_info.stdout_lines }}"

  - name: Remove script
    ansible.builtin.file:
      path: /root/instalAgenteAWS.sh
      state: absent
