---
- name: Playbook lsb_release
  hosts: '{{ target }}'
  become: True
  tasks:
    - name: Ejecutar comando lsb_release remotamente
      command: lsb_release -a
      register: salida
    - name: Mostrar salida
      debug:
        var: salida
