---
- name: Ansible Fetch OS Version
  gather_facts: true
  hosts: '{{ target }}'

  tasks:
    - name: 'System OS details'
      debug:
        msg: OS Version = {{ ansible_distribution }} {{ ansible_distribution_version}} {{ ansible_distribution_release}}

