---  
- name: post SUSE Manager
  hosts: sap
  become: yes
  tasks: 
  - name: Ensure salt-minion service is started
    ansible.builtin.service:
      name: salt-minion
      state: started

  - name: Pause for 20 segundos
    ansible.builtin.pause:
      seconds: 20

  - name: Ensure salt-minion service is restarted
    ansible.builtin.service:
      name: salt-minion
      state: restarted

  - name: write script using jinja2
    ansible.builtin.template:
      src: vaciaRepo.j2
      dest: /root/vaciaRepo.sh

  - name: Execute script
    command: sh /root/vaciaRepo.sh
    ignore_errors: true

  - name: Remove file
    ansible.builtin.file:
      path: /root/vaciaRepo.sh
      state: absent
