---  
- name: prepare SUSE Manager config
  hosts: '{{ target }}'
  become: yes
  vars:
    target: g500603vm201
    pais: CL
    servicePack: 4
    sap: ""
  tasks: 
  - name: Use Jinja2 template to configure ServicePack level
    template:
      src: susemanagerConfBkp.j2
      dest: /etc/salt/minion.d/susemanager.conf.bkp
    tags:
      script

  - name: Copy file to original
    ansible.builtin.copy:
          src: /etc/salt/minion.d/susemanager.conf.bkp
          remote_src: true
          dest: /etc/salt/minion.d/susemanager.conf
    tags:
      copy
