---
- name: prepare SUSE Manager config
  hosts: '{{ target }}'
  become: yes
  vars:
    pais: CL
    servicePack: 4
  tasks:
  - name: Use Jinja2 template to configure ServicePack level
    template:
      src: susemanagerConfSAPBkp.j2
      dest: /etc/salt/minion.d/susemanager.conf.bkp

  - name: Copy file to original
    ansible.builtin.copy:
          src: /etc/salt/minion.d/susemanager.conf.bkp
          remote_src: true
          dest: /etc/salt/minion.d/susemanager.conf

