---  
- name: vacia repositorios excepto del susemanager
  hosts: '{{ target }}'
  become: yes
  tasks: 
  - name: write script using jinja2
    ansible.builtin.template:
      src: vaciaRepo.j2
      dest: /root/vaciaRepo.sh
    tags:
      script

  - name: Execute script
    command: sh /root/vaciaRepo.sh
    ignore_errors: true
    tags:
      command

  - name: Remove file
    ansible.builtin.file:
      path: /root/vaciaRepo.sh
      state: absent
    tags:
      removeScript
